export const books = [
  // Perjanjian Lama
  { code: "Kej", name: "Kejadian", chapters: 50 },
  { code: "Kel", name: "Keluaran", chapters: 40 },
  { code: "Im", name: "Imamat", chapters: 27 },
  { code: "Bil", name: "Bilangan", chapters: 36 },
  { code: "Ul", name: "Ulangan", chapters: 34 },
  { code: "Yos", name: "Yosua", chapters: 24 },
  { code: "Hak", name: "Hakim-hakim", chapters: 21 },
  { code: "Rut", name: "Rut", chapters: 4 },
  { code: "1Sam", name: "1 Samuel", chapters: 31 },
  { code: "2Sam", name: "2 Samuel", chapters: 24 },
  { code: "1Raj", name: "1 Raja-raja", chapters: 22 },
  { code: "2Raj", name: "2 Raja-raja", chapters: 25 },
  { code: "1Taw", name: "1 Tawarikh", chapters: 29 },
  { code: "2Taw", name: "2 Tawarikh", chapters: 36 },
  { code: "Ezra", name: "Ezra", chapters: 10 },
  { code: "Neh", name: "Nehemia", chapters: 13 },
  { code: "Est", name: "Ester", chapters: 10 },
  { code: "Ayb", name: "Ayub", chapters: 42 },
  { code: "Maz", name: "Mazmur", chapters: 150 },
  { code: "Ams", name: "Amsal", chapters: 31 },
  { code: "Peng", name: "Pengkhotbah", chapters: 12 },
  { code: "Kid", name: "Kidung Agung", chapters: 8 },
  { code: "Yes", name: "Yesaya", chapters: 66 },
  { code: "Yer", name: "Yeremia", chapters: 52 },
  { code: "Rat", name: "Ratapan", chapters: 5 },
  { code: "Yeh", name: "Yehezkiel", chapters: 48 },
  { code: "Dan", name: "Daniel", chapters: 12 },
  { code: "Hos", name: "Hosea", chapters: 14 },
  { code: "Yoel", name: "Yoel", chapters: 3 },
  { code: "Amos", name: "Amos", chapters: 9 },
  { code: "Oba", name: "Obaja", chapters: 1 },
  { code: "Yun", name: "Yunus", chapters: 4 },
  { code: "Mik", name: "Mikha", chapters: 7 },
  { code: "Nah", name: "Nahum", chapters: 3 },
  { code: "Hab", name: "Habakuk", chapters: 3 },
  { code: "Zef", name: "Zefanya", chapters: 3 },
  { code: "Hag", name: "Hagai", chapters: 2 },
  { code: "Zak", name: "Zakharia", chapters: 14 },
  { code: "Mal", name: "Maleakhi", chapters: 4 },

  // Perjanjian Baru
  { code: "Mat", name: "Matius", chapters: 28 },
  { code: "Mrk", name: "Markus", chapters: 16 },
  { code: "Luk", name: "Lukas", chapters: 24 },
  { code: "Yoh", name: "Yohanes", chapters: 21 },
  { code: "Kis", name: "Kisah Para Rasul", chapters: 28 },
  { code: "Rom", name: "Roma", chapters: 16 },
  { code: "1Kor", name: "1 Korintus", chapters: 16 },
  { code: "2Kor", name: "2 Korintus", chapters: 13 },
  { code: "Gal", name: "Galatia", chapters: 6 },
  { code: "Ef", name: "Efesus", chapters: 6 },
  { code: "Flp", name: "Filipi", chapters: 4 },
  { code: "Kol", name: "Kolose", chapters: 4 },
  { code: "1Tes", name: "1 Tesalonika", chapters: 5 },
  { code: "2Tes", name: "2 Tesalonika", chapters: 3 },
  { code: "1Tim", name: "1 Timotius", chapters: 6 },
  { code: "2Tim", name: "2 Timotius", chapters: 4 },
  { code: "Tit", name: "Titus", chapters: 3 },
  { code: "Flm", name: "Filemon", chapters: 1 },
  { code: "Ibr", name: "Ibrani", chapters: 13 },
  { code: "Yak", name: "Yakobus", chapters: 5 },
  { code: "1Pet", name: "1 Petrus", chapters: 5 },
  { code: "2Pet", name: "2 Petrus", chapters: 3 },
  { code: "1Yoh", name: "1 Yohanes", chapters: 5 },
  { code: "2Yoh", name: "2 Yohanes", chapters: 1 },
  { code: "3Yoh", name: "3 Yohanes", chapters: 1 },
  { code: "Yud", name: "Yudas", chapters: 1 },
  { code: "Wah", name: "Wahyu", chapters: 22 },
];
